In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available
Using GPU: Tesla T4


## Creating Tensors

In [ ]:
# using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2341, 0.1664, 0.6486],
        [0.3168, 0.8596, 0.9683]])

In [ ]:
# manual_seed
torch.manual_seed(100) # just like random_state
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
print("using arange -> ", torch.arange(0,10,2))

print("using linspace ->", torch.linspace(0,10,10))

print("using eye -> ", torch.eye(5))

print("using full ->", torch.full((3, 3), 5))

using arange ->  tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3473789761932845409]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [ ]:
 # find data type
 x.dtype

torch.int64

In [ ]:
# assgin data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operations

In [ ]:
x = torch.rand(2,2)
print(x)

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])


In [ ]:
# addition
x + 2
# subtraction
x - 2
# multiplicatoin
x * 2
# division
x / 2
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# pow
x ** 2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [ ]:
a = torch.rand(2,2)
b = torch.rand(2,2)

print(a)
print(b)

tensor([[0.1784, 0.8238],
        [0.5557, 0.9770]])
tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])


In [ ]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.1784, 0.8238],
        [0.5557, 0.4878]])

In [ ]:
# abs
c = torch.tensor([1, -2, 3, -4])
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [ ]:
# total sum
torch.sum(e)
# column wise sum
torch.sum(e, dim=0)
# row wise sum
torch.sum(e, dim=1)

tensor([17., 25.])

In [ ]:
# mean
torch.mean(e)

tensor(7.)

In [ ]:
# median
torch.median(e)

tensor(7.)

In [ ]:
# max and min
torch.max(e), torch.min(e)

(tensor(9.), tensor(5.))

In [ ]:
# product
torch.prod(e)

tensor(99225.)

In [ ]:
# standard deviation
torch.std(e)

tensor(1.7889)

In [ ]:
# variance
torch.var(e)

tensor(3.2000)

In [ ]:
# argmax and argmin
torch.argmax(e), torch.argmin(e)

(tensor(3), tensor(0))

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0447, 0.5123, 0.9051],
        [0.5989, 0.4450, 0.7278]])
tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])


In [ ]:
m.add_(n)

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [ ]:
m

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [ ]:
n

tensor([[0.4563, 0.3389, 0.6211],
        [0.5530, 0.6896, 0.3687]])

In [ ]:
torch.relu(m)

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

In [ ]:
m.relu_()

tensor([[0.5009, 0.8512, 1.5262],
        [1.1519, 1.1346, 1.0966]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [ ]:
b = a
b

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [ ]:
b = a.clone()

In [ ]:
b

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [ ]:
a

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.8356,  0.3039],
        [ 0.6726,  0.5740,  0.9233]])

In [ ]:
b

tensor([[0.9053, 0.8356, 0.3039],
        [0.6726, 0.5740, 0.9233]])

In [ ]:
id(a, b)